# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/track_info/track_info.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'services/track_info/track_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from music_ml.protobuf.common import track_pb2 as common_dot_track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$services/track_info/track_info.proto\x12\ntrack_info\x1a\x12\x63ommon/track.proto\",\n\x10TrackInfoRequest\x12\x18\n\x10spotify_track_id\x18\x01 \x01(\t\"1\n\x11TrackInfoResponse\x12\x1c\n\x05track\x18\x01 \x01(\x0b\x32\r.common.Track2_\n\x10TrackInfoService\x12K\n\x0cGetTrackInfo\x12\x1c.track_info.TrackInfoRequest\x1a\x1d.track_info.TrackInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.track_info.track_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKINFOREQUEST']._serialized_start=72
  _globals['_TRACKINFOREQUEST']._serialized_end=116
  _globals['_TRACKINFORESPONSE']._serialized_start=118
  _globals['_TRACKINFORESPONSE']._serialized_end=167
  _globals['_TRACKINFOSERVICE']._serialized_start=169
  _globals['_TRACKINFOSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
