# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from music_ml.protobuf.services.track_search import track_search_pb2 as services_dot_track__search_dot_track__search__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/track_search/track_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackSearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchTrack = channel.unary_unary(
                '/track_search.TrackSearchService/SearchTrack',
                request_serializer=services_dot_track__search_dot_track__search__pb2.TrackSearchRequest.SerializeToString,
                response_deserializer=services_dot_track__search_dot_track__search__pb2.TrackSearchResponse.FromString,
                _registered_method=True)


class TrackSearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTrack,
                    request_deserializer=services_dot_track__search_dot_track__search__pb2.TrackSearchRequest.FromString,
                    response_serializer=services_dot_track__search_dot_track__search__pb2.TrackSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'track_search.TrackSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('track_search.TrackSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackSearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/track_search.TrackSearchService/SearchTrack',
            services_dot_track__search_dot_track__search__pb2.TrackSearchRequest.SerializeToString,
            services_dot_track__search_dot_track__search__pb2.TrackSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
