# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/track_search/track_search.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'services/track_search/track_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from music_ml.protobuf.common import track_pb2 as common_dot_track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(services/track_search/track_search.proto\x12\x0ctrack_search\x1a\x12\x63ommon/track.proto\".\n\x12TrackSearchRequest\x12\x18\n\x10spotify_track_id\x18\x01 \x01(\t\"3\n\x13TrackSearchResponse\x12\x1c\n\x05track\x18\x01 \x01(\x0b\x32\r.common.Track2h\n\x12TrackSearchService\x12R\n\x0bSearchTrack\x12 .track_search.TrackSearchRequest\x1a!.track_search.TrackSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.track_search.track_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKSEARCHREQUEST']._serialized_start=78
  _globals['_TRACKSEARCHREQUEST']._serialized_end=124
  _globals['_TRACKSEARCHRESPONSE']._serialized_start=126
  _globals['_TRACKSEARCHRESPONSE']._serialized_end=177
  _globals['_TRACKSEARCHSERVICE']._serialized_start=179
  _globals['_TRACKSEARCHSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
