# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from music_ml.protobuf.services.search import search_pb2 as services_dot_search_dot_search__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/search/search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchServiceStub(object):
    """SearchService: The gRPC service definition for searching tracks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchTracks = channel.unary_unary(
                '/search.SearchService/SearchTracks',
                request_serializer=services_dot_search_dot_search__pb2.SearchServiceRequest.SerializeToString,
                response_deserializer=services_dot_search_dot_search__pb2.SearchServiceResponse.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """SearchService: The gRPC service definition for searching tracks
    """

    def SearchTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTracks,
                    request_deserializer=services_dot_search_dot_search__pb2.SearchServiceRequest.FromString,
                    response_serializer=services_dot_search_dot_search__pb2.SearchServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """SearchService: The gRPC service definition for searching tracks
    """

    @staticmethod
    def SearchTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.SearchService/SearchTracks',
            services_dot_search_dot_search__pb2.SearchServiceRequest.SerializeToString,
            services_dot_search_dot_search__pb2.SearchServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
