# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/search/search.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'services/search/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from music_ml.protobuf.common import track_pb2 as common_dot_track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cservices/search/search.proto\x12\x06search\x1a\x12\x63ommon/track.proto\"4\n\x14SearchServiceRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"M\n\x15SearchServiceResponse\x12\x1d\n\x06tracks\x18\x01 \x03(\x0b\x32\r.common.Track\x12\x15\n\rtotal_results\x18\x02 \x01(\x05\x32\\\n\rSearchService\x12K\n\x0cSearchTracks\x12\x1c.search.SearchServiceRequest\x1a\x1d.search.SearchServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.search.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHSERVICEREQUEST']._serialized_start=60
  _globals['_SEARCHSERVICEREQUEST']._serialized_end=112
  _globals['_SEARCHSERVICERESPONSE']._serialized_start=114
  _globals['_SEARCHSERVICERESPONSE']._serialized_end=191
  _globals['_SEARCHSERVICE']._serialized_start=193
  _globals['_SEARCHSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
